mysite/article/urls.py
from django.conf.urls import url
from . import views, list_views

urlpatterns = [
    url(r'^article-column/$', views.article_column, name="article_column"), 
    url(r'^rename-column/$', views.rename_article_column, name="rename_article_column"),
    url(r'^del-column/$', views.del_article_column, name="del_article_column"),
    url(r'^article-post/$', views.article_post, name="article_post"),
    url(r'^article-list/$', views.article_list, name="article_list"),
    url(r'^article-detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.article_detail, name="article_detail"),
    url(r'^del-article/$', views.del_article, name="del_article"),
    url(r'^redit-article/(?P<article_id>\d+)/$', views.redit_article, name="redit_article"),
    url(r'^list-article-titles/$', list_views.article_titles, name="article_titles"),
    url(r'^list-article-detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', list_views.article_detail, name="list_article_detail"),
    url(r'^list-article-titles/(?P<username>[-\w]+)/$', list_views.article_titles, name="author_articles"),
    url(r'^like-article/$', list_views.like_article, name="like_article"),
    url(r'^article-tag/$', views.article_tag, name="article_tag"),
    url(r'^del-article-tag/$', views.del_article_tag, name="del_article_tag"),
]

mysite/blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r"^$", views.blog_title, name="blog_title"),
    url(r'(?P<article_id>\d)/$', views.blog_article, name="blog_article"),
]

mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.flatpages import views
from django.views.generic import TemplateView

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include("blog.urls", namespace="blog", app_name="blog")),
    url(r'^account/', include("account.urls", namespace='account', app_name='account')),
    url(r'^pwd_reset/', include("password_reset.urls", namespace='pwd_reset', app_name='pwd_reset')),
    url(r'^article/', include('article.urls', namespace='article', app_name='article')),
    url(r'^home/', TemplateView.as_view(template_name="home.html"), name="home"),
    url(r'^image/', include('image.urls', namespace='image', app_name='image')),
    url(r'^course/', include('course.urls', namespace='course', app_name='course')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/article/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.core.urlresolvers import reverse
from slugify import slugify


class ArticleColumn(models.Model):
    user = models.ForeignKey(User, related_name='article_column')
    column = models.CharField(max_length=200)
    created = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.column


class ArticleTag(models.Model):
    author = models.ForeignKey(User, related_name="tag")
    tag = models.CharField(max_length=500)

    def __str__(self):
        return self.tag

class ArticlePost(models.Model):
    author = models.ForeignKey(User, related_name="article")
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=500)
    column = models.ForeignKey(ArticleColumn, related_name="article_column")
    body = models.TextField()
    created = models.DateTimeField(default=timezone.now())   
    updated = models.DateTimeField(auto_now=True)
    users_like = models.ManyToManyField(User, related_name="articles_like", blank=True)
    article_tag = models.ManyToManyField(ArticleTag, related_name='article_tag', blank=True)

    class Meta:
        #ordering = ("title",)
        ordering = ("-updated",)
        index_together = (('id', 'slug'),)   

    def __str__(self):
        return self.title

    def save(self, *args, **kargs):   
        self.slug = slugify(self.title)   
        super(ArticlePost, self).save(*args, **kargs)

    def get_absolute_url(self):   
        return reverse("article:article_detail", args=[self.id, self.slug])

    def get_url_path(self):
        #return "/article/read-article/{0}/{1}".format(self.id, self.slug)
        return reverse("article:list_article_detail", args=[self.id, self.slug])


class Comment(models.Model):
    article = models.ForeignKey(ArticlePost, related_name="comments") 
    commentator = models.CharField(max_length=90)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created',) 

    def __str__(self):
        return "Comment by {0} on {1}".format(self.commentator.username, self.article)

mysite/article/forms.py
from django import forms
from .models import ArticleColumn, ArticlePost, Comment, ArticleTag

class ArticleColumnForm(forms.ModelForm):
    class Meta:
        model = ArticleColumn
        fields = ("column",)

class ArticlePostForm(forms.ModelForm):
    class Meta:
        model = ArticlePost
        fields = ("title", "body")

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("commentator", "body",)

class ArticleTagForm(forms.ModelForm):
    class Meta:
        model = ArticleTag
        fields = ('tag', )

mysite/article/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django.http import HttpResponse

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .models import ArticleColumn, ArticlePost, ArticleTag
from .forms import ArticleColumnForm, ArticlePostForm, ArticleTagForm

import json

@login_required(login_url='/account/login/')
@csrf_exempt 
def article_column(request):
    if request.method == "GET":
        columns = ArticleColumn.objects.filter(user=request.user)
        column_form = ArticleColumnForm()
        return render(request, "article/column/article_column.html", {"columns":columns, 'column_form':column_form})

    if request.method == "POST":
        column_name = request.POST['column']
        columns = ArticleColumn.objects.filter(user_id=request.user.id, column=column_name)
        if columns:
            return HttpResponse('2')
        else:
            ArticleColumn.objects.create(user=request.user, column=column_name)
            return HttpResponse("1")

@login_required(login_url='/account/login')
@require_POST
@csrf_exempt
def rename_article_column(request):
    column_name = request.POST["column_name"]
    column_id = request.POST['column_id']
    try:
        line = ArticleColumn.objects.get(id=column_id)   
        line.column = column_name   
        line.save()
        return HttpResponse("1")
    except:
        return HttpResponse("0")


@login_required(login_url='/account/login')
@require_POST
@csrf_exempt
def del_article_column(request):
    column_id = request.POST["column_id"]
    try:
        line = ArticleColumn.objects.get(id=column_id)
        line.delete() 
        return HttpResponse("1")
    except:
        return HttpResponse("2")

@login_required(login_url='/account/login')
@csrf_exempt
def article_post(request):
    if request.method=="POST":
        article_post_form = ArticlePostForm(data=request.POST)
        if article_post_form.is_valid():
            cd = article_post_form.cleaned_data
            try:
                new_article = article_post_form.save(commit=False)
                new_article.author = request.user
                new_article.column = request.user.article_column.get(id=request.POST['column_id'])
                new_article.save()
                tags = request.POST['tags']
                if tags:
                    for atag in json.loads(tags):
                        tag = request.user.tag.get(tag=atag) 
                        new_article.article_tag.add(tag) 

                
                return HttpResponse("1")
            except:
                return HttpResponse("2")
        else:
            return HttpResponse("3")
    else:
        article_post_form = ArticlePostForm()
        article_columns = request.user.article_column.all() 
        article_tags = request.user.tag.all()
        return render(request, "article/column/article_post.html", {"article_post_form":article_post_form, "article_columns":article_columns, "article_tags":article_tags})


@login_required(login_url='/account/login')
def article_list(request):
    #articles = ArticlePost.objects.filter(author=request.user) 
    #return render(request, "article/column/article_list.html", {"articles":articles})
    articles_list = ArticlePost.objects.filter(author=request.user)
    paginator = Paginator(articles_list, 2)
    page = request.GET.get('page')   
    try:
        current_page = paginator.page(page)    
        articles = current_page.object_list    
    except PageNotAnInteger:    
        current_page = paginator.page(1)
        articles = current_page.object_list
    except EmptyPage:    
        current_page = paginator.page(paginator.num_pages)    
        articles = current_page.object_list
    return render(request, "article/column/article_list.html", {"articles":articles, "page": current_page})


@login_required(login_url='/account/login')
def article_detail(request, id, slug):
    article = get_object_or_404(ArticlePost, id=id, slug=slug)
    return render(request, "article/column/article_detail.html", {"article":article})

@login_required(login_url='/account/login')
@require_POST
@csrf_exempt
def del_article(request):
    article_id = request.POST['article_id']
    try:
        article = ArticlePost.objects.get(id=article_id)
        article.delete()
        return HttpResponse("1")
    except:
    	return HttpResponse("2")


@login_required(login_url='/account/login')
@csrf_exempt
def redit_article(request, article_id):
    if request.method == "GET":
        article_columns = request.user.article_column.all()
        article = ArticlePost.objects.get(id=article_id)
        this_article_form = ArticlePostForm(initial={"title":article.title})
        this_article_column = article.column
        return render(request, "article/column/redit_article.html", {"article":article, "article_columns":article_columns, "this_article_column":this_article_column, "this_article_form":this_article_form})
    else:
        redit_article = ArticlePost.objects.get(id=article_id)
        try:
            redit_article.column = request.user.article_column.get(id=request.POST['column_id'])
            redit_article.title = request.POST['title']
            redit_article.body = request.POST['body']
            redit_article.save()
            return HttpResponse("1")
        except:
            return HttpResponse("2")

@login_required(login_url='/account/login')
@csrf_exempt
def article_tag(request):
    if request.method == "GET":
        article_tags = ArticleTag.objects.filter(author=request.user)
        article_tag_form = ArticleTagForm()
        return render(request, "article/tag/tag_list.html", {"article_tags":article_tags, "article_tag_form":article_tag_form})

    if request.method == "POST":
        tag_post_form = ArticleTagForm(data=request.POST)
        if tag_post_form.is_valid():
            try:
                new_tag = tag_post_form.save(commit=False)
                new_tag.author = request.user
                new_tag.save()
                return HttpResponse("1")
            except:
                return HttpResponse("the data cannot be save.")
        else:
            return HttpResponse("sorry, the form is not valid.")

@login_required(login_url='/account/login')
@require_POST
@csrf_exempt
def del_article_tag(request):
    tag_id = request.POST['tag_id']
    try:
        tag = ArticleTag.objects.get(id=tag_id)
        tag.delete()
        return HttpResponse("1")
    except:
    	return HttpResponse("2")

mysite/templates/article/column/article_column.html
{% extends "article/base.html" %}
{% load staticfiles %}
{% block title %}article column{% endblock %}
{% block content %}
<div>
    <p class="text-right"><button id= "add_column" onclick="add_column()" class="btn btn-primary">add column</button></p>
    <table class="table table-hover">
    	<tr>
    		<td>序号</td>
    		<td>栏目名称</td>
    		<td>操作</td>
    	</tr>
    	{% for column in columns %}
    	<tr>
    	    <td>{{ forloop.counter }}</td>
    	    <td>{{ column.column }}</td>
    	    <td>
                <a name="edit" href="javascript:" onclick="edit_column(this, {{ column.id }})"><span class="glyphicon glyphicon-pencil"></span></a>
                <a name="delete" href="javascript:" onclick="del_column(this, {{ column.id }})"><span class="glyphicon glyphicon-trash" style="margin-left:20px;"></span></a>
            </td>
    	</tr>
    	{% empty %}
    	<p>还没有设置栏目，太懒了。</p>
    	{% endfor %}
    </table>
</div>
</div>
<script type="text/javascript" src='{% static "js/jquery.js" %}'></script>
<script type="text/javascript" src='{% static "js/layer.js"%}'></script>
<script type="text/javascript">
function add_column(){
    var index = layer.open({
	type:1,
	skin:"layui-layer-rim",
	area: ["400px", "200px"],
	title: "新增栏目",
	content: '<div class="text-center" style="margin-top:20px"><p>请输入新的栏目名称</p><p>{{column_form.column}}</p></div>',
	btn:['确定', '取消'],
	yes: function(index, layero){
	    column_name = $('#id_column').val();
	    $.ajax({
		url:'{% url "article:article_column" %}',
		type:'POST',
		data:{"column":column_name},
		success:function(e){
		    if(e=="1"){
		    parent.location.reload();
		    layer.msg("good");
		    }else{
		        layer.msg("此栏目已有，请更换名称")
		    }
		},
	    });
	},
	btn2: function(index, layero){
	layer.close(index);
	}
    });
}

function edit_column(the, column_id){
    var name = $(the).parents("tr").children("td").eq(1).text();
    var index = layer.open({
	type: 1,
	skin: "layui-layer-rim",
        area: ["400px", "200px"],
        title: "编辑栏目",
        content: '<div class="text-center" style="margin-top:20px"><p>请编辑的栏目名称</p><p><input type="text" id="new_name" value="'+name+'"></p></div>',
        btn:['确定', '取消'],
        yes: function(index, layero){
       	    new_name = $("#new_name").val();
           	$.ajax({
            	url: "{% url 'article:rename_article_column' %}",
            	type: "POST",
            	data: {"column_id": column_id, "column_name": new_name},
            	success: function(e){
       		    if(e=="1"){
            		parent.location.reload();
            	        layer.msg("good");
            	    }else{
            		layer.msg("新的名称没有保存,修改失败。")
            	    }
            	},
            });
        },
    });
}

function del_column(the, column_id){
    var name = $(the).parents("tr").children("td").eq(1).text();
    layer.open({
	type: 1,
	skin: "layui-layer-rim",
	area: ["400px", "200px"],
	title: "删除栏目",
	content: '<div class="text-center" style="margin-top:20px"><p>是否确定删除{'+name+'}栏目</p></div>',
	btn:['确定', '取消'],
	yes: function(){
	    $.ajax({
	    url: '{% url "article:del_article_column" %}',
	    type:"POST",
	    data: {"column_id":column_id},
	    success: function(e){
	        if(e=="1"){
		    parent.location.reload();
		    layer.msg("has been deleted.");
		}else{
		    layer.msg("删除失败");
		}
	    },
	    })	
	},
    });
}


</script>

{% endblock %}

mysite/templates/article/column/article_detail.html
{% extends "article/base.html" %}

{% load staticfiles %}

{% block title %}articles list{% endblock %}

{% block content %}
<div>
    <header>
        <h1>{{ article.title }}</h1>
        <p>{{ user.username }}</p>
    </header>

    <link rel="stylesheet" href="{% static 'editor/css/editormd.preview.css' %}" />
    <div id='editormd-view'>
        <textarea id="append-test" style="display:none;">
{{ article.body }}
	    </textarea> 
    </div>

</div>
<script src='{% static "js/jquery.js" %}'></script>
<script src='{% static "editor/lib/marked.min.js" %}'></script>
<script src='{% static "editor/lib/prettify.min.js" %}'></script>
<script src='{% static "editor/lib/raphael.min.js" %}'></script>
<script src='{% static "editor/lib/underscore.min.js" %}'></script>
<script src='{% static "editor/lib/sequence-diagram.min.js" %}'></script>
<script src='{% static "editor/lib/flowchart.min.js" %}''></script>
<script src='{% static "editor/lib/jquery.flowchart.min.js" %}'></script>
<script src='{% static "editor/editormd.js" %}'></script>

<script type="text/javascript">
$(function(){
	editormd.markdownToHTML("editormd-view", {
        htmlDecode      : "style,script,iframe",  // you can filter tags decode
        emoji           : true,
        taskList        : true,
        tex             : true,  // 默认不解析
        flowChart       : true,  // 默认不解析
        sequenceDiagram : true,  // 默认不解析
    });
});
</script>
{% endblock %}

mysite/templates/article/column/article_list.html
{% extends "article/base.html" %}
{% load staticfiles %}

{% block title %}articles list{% endblock %}

{% block content %}
<div>
    <table class="table table-hover">
    	<tr>
    	    <td>序号</td>
    	    <td>标题</td>
            <td>栏目</td>
    	    <td>操作</td>
    	</tr>
    	{% for article in articles %}
    	<tr id={{ article.id }}>
    	    <td>{{ forloop.counter }}</td>
    	    <td><a href="{{ article.get_absolute_url }}">{{ article.title }}</a></td>
            <td>{{ article.column }}</td>
    	    <td>
                <a name="edit" href="{% url 'article:redit_article' article.id %}"><span class="glyphicon glyphicon-pencil"></span></a>
                <a nane="delete" href="javascript:" onclick="del_article(this, {{ article.id }})"><span class="glyphicon glyphicon-trash" style="margin-left:20px;"></span></a>
            </td>
    	</tr>
    	{% endfor %}
    </table>
    {% include "paginator.html" %}
</div>
<script type="text/javascript" src='{% static "js/jquery.js" %}'></script>
<script type="text/javascript" src="{% static 'js/layer.js'%}"></script>
<script type="text/javascript">
function del_article(the, article_id){
    var article_name = $(the).parents("tr").children("td").eq(1).text();
        layer.open({
	    type: 1,
	    skin: "layui-layer-rim",
	    area: ["400px", "200px"],
	    title: "删除文章",
	    content: '<div class="text-center" style="margin-top:20px"><p>是否确定删除《'+article_name+'》</p></div>',
	    btn:['确定', '取消'],
	    yes: function(){
		$.ajax({
		    url: '{% url "article:del_article" %}',
		    type:"POST",
		    data: {"article_id":article_id},
		    success: function(e){
			if(e=="1"){
			    parent.location.reload();
			    layer.msg("has been deleted.");
			}else{
			    layer.msg("删除失败");
			}
						
		    },
		})	
	    },
	});
    }
</script>

{% endblock %}

mysite/templates/article/column/article_post.html
{% extends "article/base.html" %}
{% load staticfiles %}
{% block title %}article column{% endblock %}
{% block content %}
<link rel="stylesheet" href="{% static 'editor/css/style.css' %}">
<link rel="stylesheet" href="{% static 'editor/css/editormd.css' %}">
<div style="margin-left:10px">
    <form class="form-horizontal" action="." method="post">{% csrf_token %}
        <div class="row" style="margin-top: 10px;">
            <div class="col-md-2 text-right"><span>标题:</span></div>
            <div class="col-md-10 text-left">{{article_post_form.title}}</div>
        </div>
        <div class="row" style="margin-top: 10px;">
            <div class="col-md-2 text-right"><span>栏目:</span></div>
            <div class="col-md-10 text-left">
            	<select id="which_column">
            	    {% for column in article_columns %}
            	    <option value="{{column.id}}">{{column.column}}</option>
            	    {% endfor %}
            	</select>
            </div>
        </div>
        <div class="row" style="margin-top: 10px;">
            <div class="col-md-2 text-right"><span>文章标签:</span></div>
            <div class="col-md-10 text-left">
                {% for tag in article_tags %}
                <label class="checkbox-inline">
                    <input class="tagcheckbox" type="checkbox" id="{{ tag.id }}" name="article_tag" value="{{ tag.tag }}"> {{ tag.tag }}
                </label>
                {% empty %}
                <p>You have not type tags for articles. Please <a href="{% url 'article:article_tag' %}">input your tags</a></p>
                {% endfor %}
            </div>
        </div>

        <div class="row" style="margin-top: 10px;">
        	<div class="col-md-2 text-right"><span>内容:</span></div>
        	<!--div class="col-md-10 text-left">{{article_post_form.body}}</div-->
            <div id="editormd" class="col-md-10 text-left">
                <textarea style="display:none;" id="id_body"></textarea>
            </div>
        </div>
        <div class="row">
            <input type="button" class="btn btn-primary btn-lg" value="发布" onclick="publish_article()">
        </div>
    </form>
</div>
<script type="text/javascript" src='{% static "js/jquery.js" %}'></script>
<script type="text/javascript" src="{% static 'js/layer.js'%}"></script>
<script type="text/javascript" src='{% static "editor/editormd.min.js" %}'></script>
<script type="text/javascript" src="{% static 'js/json2.js' %}"></script>
<script type="text/javascript">
function publish_article(){
    var title = $("#id_title").val();
    var column_id = $("#which_column").val();
    var body = $("#id_body").val();
    var article_tags = [];
    $.each($("input[name='article_tag']:checked"), function(){article_tags.push($(this).val());});
    $.ajax({
        url: "{% url 'article:article_post' %}",
        type: "POST",
        data: {"title":title, "body":body, "column_id":column_id, "tags":JSON.stringify(article_tags)},
        success: function(e){
            if(e=="1"){
        	layer.msg("successful");
                location.href = "{% url 'article:article_list' %}";
            }else if(e=="2"){
        	layer.msg("sorry.") ;
            }else{
        	layer.msg("是不是有没有填写的项目？都必须写，不能空。");
            }
        },
    });
}

$(function() {
    var editor = editormd("editormd", {
        width   : "100%",
        height  : 640,
        syncScrolling : "single",
        path    : "{% static 'editor/lib/' %}"
    });
});

</script>
{% endblock %}

mysite/templates/article/column/redit_article.html
{% extends "article/base.html" %}

{% load staticfiles %}

{% block title %}article column{% endblock %}

{% block content %}
<link rel="stylesheet" href="{% static 'editor/css/style.css' %}">
<link rel="stylesheet" href="{% static 'editor/css/editormd.css' %}">
<div>
<div style="margin-left:10px">
    <form class="form-horizontal" action="." method="post">{% csrf_token %}
        <div class="row" style="margin-top: 10px;">
            <div class="col-md-2 text-right"><span>标题:</span></div>
            <div class="col-md-10 text-left">{{this_article_form.title}}</div>
        </div>
        <div class="row" style="margin-top: 10px;">
            <div class="col-md-2 text-right"><span>栏目:</span></div>
            <div class="col-md-10 text-left">
            	<select id="which_column">
            	    {% for column in article_columns %}
                        {% if column == this_article_column.column %}   
            	            <option value="{{column.id}}" selected="selected">{{column.column}}</option>    
                        {% else %}
                            <option value="{{column.id}}">{{column.column}}</option>
                        {% endif %}
            	    {% endfor %}
            	</select>
            </div>
        </div>
        <div  class="row" style="margin-top: 10px;">
        	<div class="col-md-2 text-right"><span>内容:</span></div>
        	<div id="editormd" class="col-md-10 text-left"><!--{{article_post_form.body}}-->
                <textarea style="display:none;" id="id_body">
{{article.body}}   
                </textarea>
        	</div>
        </div>
        <div class="row">
            <input type="button" class="btn btn-primary btn-lg" value="发布" onclick="redit_article()">
        </div>
    </form>

</div>
</div>
<script type="text/javascript" src='{% static "js/jquery.js" %}'></script>
<script type="text/javascript" src='{% static "editor/editormd.min.js" %}'></script>
<script type="text/javascript" src="{% static 'js/layer.js'%}"></script>
<script type="text/javascript">
    $(function() {
        var editor = editormd("editormd", {
            width   : "100%",
            height  : 640,
            //syncScrolling : "single",
            path    : "{% static 'editor/lib/' %}",
        });
    });

function redit_article(){
    var title = $("#id_title").val();
    var column_id = $("#which_column").val();
    var body = $("#id_body").val();
    $.ajax({
        url: "{% url 'article:redit_article' article.id %}",
        type: "POST",
        data: {"title":title, "body":body, "column_id":column_id},
        success: function(e){
            if(e=="1"){
                layer.msg("successful");
                location.href = "{% url 'article:article_list' %}";
            }else{
        	layer.msg("sorry.");
            }
        },
    });
}

</script>

{% endblock %}