mysite/article/urls.py
from django.conf.urls import url
from . import views, list_views

urlpatterns = [
    url(r'^article-column/$', views.article_column, name="article_column"), 
    url(r'^rename-column/$', views.rename_article_column, name="rename_article_column"),
    url(r'^del-column/$', views.del_article_column, name="del_article_column"),
    url(r'^article-post/$', views.article_post, name="article_post"),
    url(r'^article-list/$', views.article_list, name="article_list"),
    url(r'^article-detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.article_detail, name="article_detail"),
    url(r'^del-article/$', views.del_article, name="del_article"),
    url(r'^redit-article/(?P<article_id>\d+)/$', views.redit_article, name="redit_article"),
    url(r'^list-article-titles/$', list_views.article_titles, name="article_titles"),
    url(r'^list-article-detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', list_views.article_detail, name="list_article_detail"),
    url(r'^list-article-titles/(?P<username>[-\w]+)/$', list_views.article_titles, name="author_articles"),
    url(r'^like-article/$', list_views.like_article, name="like_article"),
    url(r'^article-tag/$', views.article_tag, name="article_tag"),
    url(r'^del-article-tag/$', views.del_article_tag, name="del_article_tag"),
]

mysite/blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r"^$", views.blog_title, name="blog_title"),
    url(r'(?P<article_id>\d)/$', views.blog_article, name="blog_article"),
]

mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.flatpages import views
from django.views.generic import TemplateView

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include("blog.urls", namespace="blog", app_name="blog")),
    url(r'^account/', include("account.urls", namespace='account', app_name='account')),
    url(r'^pwd_reset/', include("password_reset.urls", namespace='pwd_reset', app_name='pwd_reset')),
    url(r'^article/', include('article.urls', namespace='article', app_name='article')),
    url(r'^home/', TemplateView.as_view(template_name="home.html"), name="home"),
    url(r'^image/', include('image.urls', namespace='image', app_name='image')),
    url(r'^course/', include('course.urls', namespace='course', app_name='course')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/article/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.core.urlresolvers import reverse
from slugify import slugify


class ArticleColumn(models.Model):
    user = models.ForeignKey(User, related_name='article_column')
    column = models.CharField(max_length=200)
    created = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.column


class ArticleTag(models.Model):
    author = models.ForeignKey(User, related_name="tag")
    tag = models.CharField(max_length=500)

    def __str__(self):
        return self.tag

class ArticlePost(models.Model):
    author = models.ForeignKey(User, related_name="article")
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=500)
    column = models.ForeignKey(ArticleColumn, related_name="article_column")
    body = models.TextField()
    created = models.DateTimeField(default=timezone.now())   
    updated = models.DateTimeField(auto_now=True)
    users_like = models.ManyToManyField(User, related_name="articles_like", blank=True)
    article_tag = models.ManyToManyField(ArticleTag, related_name='article_tag', blank=True)

    class Meta:
        #ordering = ("title",)
        ordering = ("-updated",)
        index_together = (('id', 'slug'),)   

    def __str__(self):
        return self.title

    def save(self, *args, **kargs):   
        self.slug = slugify(self.title)   
        super(ArticlePost, self).save(*args, **kargs)

    def get_absolute_url(self):   
        return reverse("article:article_detail", args=[self.id, self.slug])

    def get_url_path(self):
        #return "/article/read-article/{0}/{1}".format(self.id, self.slug)
        return reverse("article:list_article_detail", args=[self.id, self.slug])


class Comment(models.Model):
    article = models.ForeignKey(ArticlePost, related_name="comments") 
    commentator = models.CharField(max_length=90)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created',) 

    def __str__(self):
        return "Comment by {0} on {1}".format(self.commentator.username, self.article)

mysite/article/forms.py
from django import forms
from .models import ArticleColumn, ArticlePost, Comment, ArticleTag

class ArticleColumnForm(forms.ModelForm):
    class Meta:
        model = ArticleColumn
        fields = ("column",)

class ArticlePostForm(forms.ModelForm):
    class Meta:
        model = ArticlePost
        fields = ("title", "body")

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("commentator", "body",)

class ArticleTagForm(forms.ModelForm):
    class Meta:
        model = ArticleTag
        fields = ('tag', )

mysite/article/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django.http import HttpResponse

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .models import ArticleColumn, ArticlePost, ArticleTag
from .forms import ArticleColumnForm, ArticlePostForm, ArticleTagForm

import json

@login_required(login_url='/account/login/')
@csrf_exempt 
def article_column(request):
    if request.method == "GET":
        columns = ArticleColumn.objects.filter(user=request.user)
        column_form = ArticleColumnForm()
        return render(request, "article/column/article_column.html", {"columns":columns, 'column_form':column_form})

    if request.method == "POST":
        column_name = request.POST['column']
        columns = ArticleColumn.objects.filter(user_id=request.user.id, column=column_name)
        if columns:
            return HttpResponse('2')
        else:
            ArticleColumn.objects.create(user=request.user, column=column_name)
            return HttpResponse("1")

@login_required(login_url='/account/login')
@require_POST
@csrf_exempt
def rename_article_column(request):
    column_name = request.POST["column_name"]
    column_id = request.POST['column_id']
    try:
        line = ArticleColumn.objects.get(id=column_id)   
        line.column = column_name   
        line.save()
        return HttpResponse("1")
    except:
        return HttpResponse("0")


@login_required(login_url='/account/login')
@require_POST
@csrf_exempt
def del_article_column(request):
    column_id = request.POST["column_id"]
    try:
        line = ArticleColumn.objects.get(id=column_id)
        line.delete() 
        return HttpResponse("1")
    except:
        return HttpResponse("2")

@login_required(login_url='/account/login')
@csrf_exempt
def article_post(request):
    if request.method=="POST":
        article_post_form = ArticlePostForm(data=request.POST)
        if article_post_form.is_valid():
            cd = article_post_form.cleaned_data
            try:
                new_article = article_post_form.save(commit=False)
                new_article.author = request.user
                new_article.column = request.user.article_column.get(id=request.POST['column_id'])
                new_article.save()
                tags = request.POST['tags']
                if tags:
                    for atag in json.loads(tags):
                        tag = request.user.tag.get(tag=atag) 
                        new_article.article_tag.add(tag) 

                
                return HttpResponse("1")
            except:
                return HttpResponse("2")
        else:
            return HttpResponse("3")
    else:
        article_post_form = ArticlePostForm()
        article_columns = request.user.article_column.all() 
        article_tags = request.user.tag.all()
        return render(request, "article/column/article_post.html", {"article_post_form":article_post_form, "article_columns":article_columns, "article_tags":article_tags})


@login_required(login_url='/account/login')
def article_list(request):
    #articles = ArticlePost.objects.filter(author=request.user) 
    #return render(request, "article/column/article_list.html", {"articles":articles})
    articles_list = ArticlePost.objects.filter(author=request.user)
    paginator = Paginator(articles_list, 2)
    page = request.GET.get('page')   
    try:
        current_page = paginator.page(page)    
        articles = current_page.object_list    
    except PageNotAnInteger:    
        current_page = paginator.page(1)
        articles = current_page.object_list
    except EmptyPage:    
        current_page = paginator.page(paginator.num_pages)    
        articles = current_page.object_list
    return render(request, "article/column/article_list.html", {"articles":articles, "page": current_page})


@login_required(login_url='/account/login')
def article_detail(request, id, slug):
    article = get_object_or_404(ArticlePost, id=id, slug=slug)
    return render(request, "article/column/article_detail.html", {"article":article})

@login_required(login_url='/account/login')
@require_POST
@csrf_exempt
def del_article(request):
    article_id = request.POST['article_id']
    try:
        article = ArticlePost.objects.get(id=article_id)
        article.delete()
        return HttpResponse("1")
    except:
    	return HttpResponse("2")


@login_required(login_url='/account/login')
@csrf_exempt
def redit_article(request, article_id):
    if request.method == "GET":
        article_columns = request.user.article_column.all()
        article = ArticlePost.objects.get(id=article_id)
        this_article_form = ArticlePostForm(initial={"title":article.title})
        this_article_column = article.column
        return render(request, "article/column/redit_article.html", {"article":article, "article_columns":article_columns, "this_article_column":this_article_column, "this_article_form":this_article_form})
    else:
        redit_article = ArticlePost.objects.get(id=article_id)
        try:
            redit_article.column = request.user.article_column.get(id=request.POST['column_id'])
            redit_article.title = request.POST['title']
            redit_article.body = request.POST['body']
            redit_article.save()
            return HttpResponse("1")
        except:
            return HttpResponse("2")

@login_required(login_url='/account/login')
@csrf_exempt
def article_tag(request):
    if request.method == "GET":
        article_tags = ArticleTag.objects.filter(author=request.user)
        article_tag_form = ArticleTagForm()
        return render(request, "article/tag/tag_list.html", {"article_tags":article_tags, "article_tag_form":article_tag_form})

    if request.method == "POST":
        tag_post_form = ArticleTagForm(data=request.POST)
        if tag_post_form.is_valid():
            try:
                new_tag = tag_post_form.save(commit=False)
                new_tag.author = request.user
                new_tag.save()
                return HttpResponse("1")
            except:
                return HttpResponse("the data cannot be save.")
        else:
            return HttpResponse("sorry, the form is not valid.")

@login_required(login_url='/account/login')
@require_POST
@csrf_exempt
def del_article_tag(request):
    tag_id = request.POST['tag_id']
    try:
        tag = ArticleTag.objects.get(id=tag_id)
        tag.delete()
        return HttpResponse("1")
    except:
    	return HttpResponse("2")

mysite/templates/article/list/article_detail.html
{% extends "base.html" %}
{% load article_tags %}
{% load staticfiles %}

{% block title %}{{ article.title }}{% endblock %}

{% block content %}

{% with total_likes=article.users_like.count users_like=article.users_like.all %}

<div class="container">
<div class="col-md-9">
    <header>
        <h1>{{ article.title }}</h1>
        <p>
            <a href="{% url 'article:author_articles' article.author.username %}">
                {{ article.author.username }}
            </a>
            <span style="margin-left:20px" class="glyphicon glyphicon-thumbs-up">{{ total_likes }}like{{ total_likes | pluralize }}</span>
            <span style="margin-left: 20px">{{ total_views }}view{{ total_views | pluralize }}</span>
        </p>
        <p> <span style="margin-right: 10px"><strong>Tags:</strong></span> {{ article.article_tag.all | join:", "}}</p>
    </header>

    <link rel="stylesheet" href="{% static 'editor/css/editormd.preview.css' %}" />
    <div id='editormd-view'>
        <!--textarea id="append-test" style="display:none;">
{{ article.body }}
        </textarea-->
{{ article.body | markdown }} 
    </div>
     <div>
        <p class="text-center">
            <a onclick="like_article({{article.id}}, 'like')" href="#"><span class="glyphicon glyphicon-thumbs-up">like</span></a> 
            <a onclick="like_article({{article.id}}, 'unlike')" href="#"><span style="margin-left: 15px;" class="glyphicon glyphicon-thumbs-down">unlike</span></a>
        </p>
    </div>
    <div>
        <p class="text-center"><strong>点赞本文的读者</strong></p>    
        {% for user in article.users_like.all %}
        <p class="text-center">{{ user.username }}</p>
        {% empty %}  
        <p class="text-center">还没有人对此文章表态</p>
        {% endfor %}
    </div>
    <hr>
    <div>
        <h3><span class="glyphicon glyphicon-bullhorn"></span>本文有{{ comments.count }}评论</h3>
        {% for comment in article.comments.all %}
        <div>
            <p><strong>{{ comment.commentator }}</strong>说：</p>
            <p style="margin-left:40px;">{{ comment.body }}</p>
        </div>
        {% empty %}
        <p>没有评论</p>
        {% endfor %}

        <h3><span class="glyphicon glyphicon-send"></span>看文章，发评论，不要沉默</h3>
        <form action="." method="post" class="form-horizontal" role="form">{% csrf_token %}
            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 control-label">评论员</label>
                <div class="col-sm-10">
                    {{ comment_form.commentator}}
                </div>
            </div>
            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 control-label">评论</label>
                <div class="col-sm-10">
                    {{ comment_form.body }}
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <p><input type="submit" name="" value="发评论" class="btn btn-primary"></p>
                </div>
            </div>
        </form>
    </div>

</div>
<div class="col-md-3">
    <p class="text-center"><h3>最受欢迎文章</h3></p>
    <ol>
        {% for article_rank in most_viewed %}
        <li>
            <a href="{{article_rank.get_url_path}}">{{ article_rank.title }}</a>
        </li>
        {% endfor %}
    </ol>
    <hr>
    <p class="text-center"><h3>最新文章</h3></p>
    <div>{% latest_articles 4 %}</div>

    <hr>
    <p class="text-center"><h3>最多评论文章</h3></p>
    {% most_commented_articles as most_comments %}  
    <div><ul>
        {% for comment_article in most_comments %}
        <li>
            <a href="{{comment_article.get_url_path}}">{{ comment_article.title }}</a>
        </li>
        {% endfor %}
    </ul></div>

    <hr>
    <p class="text-center"><h3>推荐相似文章</h3></p>
    <div>        
        {% for similar in similar_articles %}
        <p><a href="{{ similar.get_url_path }}">{{ similar.title }}</a></p>
        {% empty %}
        <p>Sorry, 没有相似文章</p>
        {% endfor %}
    </div>
</div>

</div>
<script src='{% static "js/jquery.js" %}'></script>
<script src='{% static "editor/lib/marked.min.js" %}'></script>
<script src='{% static "editor/lib/prettify.min.js" %}'></script>
<script src='{% static "editor/lib/raphael.min.js" %}'></script>
<script src='{% static "editor/lib/underscore.min.js" %}'></script>
<script src='{% static "editor/lib/sequence-diagram.min.js" %}'></script>
<script src='{% static "editor/lib/flowchart.min.js" %}''></script>
<script src='{% static "editor/lib/jquery.flowchart.min.js" %}'></script>
<script src='{% static "editor/editormd.js" %}'></script>
<script type="text/javascript" src="{% static 'js/layer.js'%}"></script>
<script type="text/javascript">
$(function(){
	editormd.markdownToHTML("editormd-view", {
        htmlDecode      : "style,script,iframe",  // you can filter tags decode
        emoji           : true,
        taskList        : true,
        tex             : true,  // 默认不解析
        flowChart       : true,  // 默认不解析
        sequenceDiagram : true,  // 默认不解析
    });
});

function like_article(id,action){
    $.ajax({
        url: "{% url 'article:like_article' %}",
        type: "POST",
        data: {"id":id, "action":action},
        success: function(e){
            if(e=="1"){
                layer.msg("感谢点赞");
                window.location.reload();
            }else{
                layer.msg("我会继续努力");
                window.location.reload();
            }
        },
    });
}
</script>
{% endwith %}  
{% endblock %}

mysite/templates/article/list/article_titles.html
{% extends "base.html" %}
{% load article_tags %}
{% block title %} articles {% endblock %}

{% block content %}
<div class="row text-center vertical-middle-sm">
    <h1>阅读，丰富头脑，善化行为</h1>
    <p>这里已经有{% total_articles %}篇文章供你阅读</p>
</div>
<div class="container">
    {% for article in articles %}
    <div class="list-group">
        <a href="{{article.get_url_path}}" class="list-group-item active">
            <h4 class="list-group-item-heading">{{article.title}}</h4>
        </a>
        <p class="list-group-item-text">作者：<a href="{% url 'article:author_articles' article.author.username %}">{{article.author.username}}</a></p>
        <p class="list-group-item-text">概要：{{article.body|slice:'70'| linebreaks}}</p>
    </div>
    {% endfor %}
{% include "paginator.html" %}
</div>
{% endblock %}

mysite/templates/article/list/author_articles.html
{% extends "base.html" %}
{% load article_tags %}
{% load staticfiles %}

{% block title %}articles{% endblock %}

{% block content %}
<div class="row text-center vertical-middle-sm">
    <h1>阅读，丰富头脑，善化行为</h1>
</div>
<div class="container">
<div class="col-md-8">
    {% for article in articles %}
    <div class="list-group">
        <a href="{{article.get_url_path}}" class="list-group-item active"><h4 class="list-group-item-heading">{{article.title}}</h4></a>
      	<p class="list-group-item-text">作者：<a href="{% url 'article:author_articles' article.author.username %}">{{article.author.username}}</a></p>
       	<p class="list-group-item-text">概要：{{article.body|slice:'70'|linebreaks}}</p>
    </div>
    {% endfor %}
{% include "paginator.html" %}
</div>
<div class="col-md-4">
<div>
    {% if userinfo.photo %}
    <img src="{{ userinfo.photo | striptags }}" class="img-circle" id="my_photo" name="user_face">
    {% else %}
    <img name="user_face" src="{% static 'images/newton.jpg' %}" class="img-circle" id="my_photo">
    {% endif %}
</div>
<div>
    <p>{{ user.username }}</p>
    <p>共发表文章{% author_total_articles user %}篇</p>
    {% if userinfo %}
    <p>{{ userinfo.company }}
    <p>{{ userinfo.aboutme }}</p>
{% else %}
<p>这个作者太懒了，什么也没有留下。</p>
{% endif %}
</div>
</div>
</div>
{% endblock %}

mysite/templates/article/list/latest_articles.html
<ul>
    {% for article in latest_articles %}
    <li>
    	<a href="{{ article.get_url_path }}">{{ article.title }}</a>
    </li>
    {% endfor %}
</ul>